name: Daily Share Trading Scraper

on:
  schedule:
    - cron: "0 12 * * *" # Every day at 12:00 UTC
  workflow_dispatch: # Allow manual run from GitHub UI

jobs:
  scrape-and-save:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pandas selenium lxml
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          if [ ! -f /usr/bin/chromedriver ]; then sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver; fi

      - name: Run scraper script
        run: python daily_scraper.py

      - name: Upload CSV as artifact
        uses: actions/upload-artifact@v4
        with:
          name: daily_share_statistics_csv
          path: output/
